name: Build and Push to GitLab Container Registry

on:
  push:
    branches:
      - master  # Adjust this to the branch you want to trigger the workflow on
    paths:
      - 'front-end/peer-prep'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to GitLab Container Registry
      run: echo ${{ secrets.DOCKER }} | docker login -u ${{ secrets.zenithyap }}
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1     
      
    - name: Build and push        
      uses: docker/build-push-action@v2
      with: 
        context: .
        file: ./Dockerfile          
        push: true
        tags: registry.gitlab.com/***
    
